clear
ls
alias ls="ls -a"
alias refresh="cd && cp -r storage/shared/termux/.bashrc ./"
alias store="cd && cp -r ./.bashrc storage/shared/termux/.bashrc && cp -r ./.bashrc storage/shared/github/conf/"
alias x="exit"
alias sd="cd && cd storage/shared/"
alias nano="nano -x"
alias n="nano -x"
alias www="cd && cd storage/shared/dev"
alias clean="apt clean && apt autoclean && apt autoremove && npm cache clear -f"
alias update="apt update && apt upgrade && npm install -g npm stable && clean"
alias setup="update && apt install nano nodejs-lts && npm -v && npm install -g sass"
echo "dir: g, sd, www"
echo "system : setup, update, clean"
echo "bashrc : refresh, store"
echo "git: push"
echo "node: scss"
alias scss="sass --watch --no-source-map"
alias g="sd && cd github"
alias push="git add * && git commit -m 'update' && git push origin master"
